# Generated by Django 4.2.1 on 2023-05-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openai_plus", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Query",
            new_name="ChatQuery",
        ),
    ]
