services:

  # Database service 
  db:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql_data:/var/lib/mysql

  # Django service
  openai:
    build: .
    container_name: chill_container
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    env_file: ./.env
    depends_on:
      - db

  # Nginx service
  nginx:
    image: nginx:latest
    # command: nginx -g "daemon off;"
    container_name: nginx_container
    ports:
      - "8040:8020"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - .:/app
    depends_on:
      - openai
