services:

  # Database service 
  db:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql_data:/var/lib/mysql

  # Django service
  openai:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chill_container
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    env_file: ./.env
    depends_on:
      - db

  # Nginx service
  nginx:
    image: nginx:latest
    # command: nginx -g "daemon off;"
    container_name: nginx_container
    ports:
      - "8040:8020"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - .:/app
    depends_on:
      - openai

  # Watcher service
  # watch basically uses the inotify feature of linux which is used for subscribing to events like modify, create, delete, move of files and directories, using this we can restart our server....not recommended for production
  watcher:
    build: 
      context: .
      dockerfile: Dockerfile.watcher
    container_name: watcher_container
    volumes:
      - ./openai_plus:/app/openai_plus
      # - ./noone:/app/noone
    command: > 
      sh -c "./watcher_actions.sh"
    depends_on:
      - openai
